const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(path.resolve(__dirname,'../Jellyfin.Plugin.WatchWheel/Web/watchWheel.js'),'utf8');
const helper=source.slice(source.indexOf('    function createWheelSound()'),source.indexOf('    function value('));
const assets=path.resolve(__dirname,'../Jellyfin.Plugin.WatchWheel/Web/Assets');
const approved={
 'spin-launch.wav':'1DA3B2450D1CF8512E5E46F400CA59394A8811421B2EB9AE8A6AF6085FD04612',
 'reel-pass-fast.wav':'DEFD0755B8A3DAC107ED562075932446F992E54EABC55B6C680D0B45983E3BFB',
 'reel-pass-slow.wav':'81BB7BE82C533013C24FBA022E2A5D0708B43E207467DDCFFB6E41BCAA648385',
 'winner-lock.wav':'D39D826A15D8F4D65C95D90FBB27C3EA4AA50FF1DEE9E86306CD7EB8F8F263B4',
 'winner-reveal.wav':'B20590695DE834541FFF58301B4C8C82385511C41E9F3CAB2A9FADCC795D65F1'
};
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
function make(delayed=false){let now=0,decodeCount=0,clipId=0;const events=[],pending=[],timers=[];const document={hidden:false};
class Audio{constructor(){this.state='running';this.destination={};this.currentTime=0;}resume(){this.state='running';return Promise.resolve()}close(){this.state='closed';events.push('close');return Promise.resolve()}decodeAudioData(bytes,yes,no){const duration=decodeCount++%2===0?5.2:3.1;if(delayed)pending.push(()=>yes({duration}));else yes({duration});}createBufferSource(){const s={playbackRate:{value:1},connect(){},disconnect(){},start(t,offset){events.push({start:true,offset,rate:s.playbackRate.value,duration:s.buffer.duration})},stop(){events.push('stop')}};return s}createOscillator(){const s={frequency:{setValueAtTime(f){s.hz=f},exponentialRampToValueAtTime(){}},connect(){},disconnect(){},start(){events.push({cue:s.hz})},stop(){events.push('cue-stop')}};return s}createGain(){return{gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}}}}
class Clip{constructor(url){this.id=++clipId;this.url=url;this.currentTime=0;this.paused=true;this.ended=false;this.duration=url.endsWith('reel-pass-fast.wav')?.205:url.endsWith('reel-pass-slow.wav')?.528:url.endsWith('spin-launch.wav')?.520:url.endsWith('winner-lock.wav')?.330:1.520;events.push({loaded:url,id:this.id})}addEventListener(name,fn){if(name==='ended')this.onended=fn}pause(){this.paused=true;events.push({paused:this.url,id:this.id})}play(){this.paused=false;this.ended=false;events.push({played:this.url,volume:this.volume,id:this.id,time:now});return Promise.resolve()}}
const scope={window:{AudioContext:Audio,Audio:Clip,ApiClient:{getUrl:x=>x},atob:s=>Buffer.from(s,'base64').toString('binary')},document,performance:{now:()=>now},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length;},Uint8Array,Promise};vm.createContext(scope);vm.runInContext(helper+';this.sfx=createWheelSound();',scope);return{sound:scope.sfx,events,pending,document,time:t=>now=t,runTimers:()=>{timers.sort((a,b)=>a.ms-b.ms).splice(0).forEach(x=>x.fn())}};}
(async()=>{
for(const [name,expected] of Object.entries(approved)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(assets,name))).digest('hex').toUpperCase();assert.equal(actual,expected,`${name} remains byte-identical to the approved candidate`)}
assert(!/popcorn-(?:spin-start|reel-tick|slow-tick|stop|reveal)-v2\.wav/.test(source),'old V2 runtime filenames are gone');
let m=make();m.sound.spin(5200);await flush();assert.equal(m.events.length,0,'no audio before gesture');m.sound.prime();m.sound.spin(6500);await flush();let start=m.events.find(e=>e.start);assert(Math.abs(start.rate-.8)<.0001,'reels stretched to animation duration');m.sound.win();await flush();assert(m.events.includes('stop'));assert.equal(m.events.filter(e=>e.start).at(-1).duration,3.1);m.sound.enabled(false);const n=m.events.filter(e=>e.start).length;m.sound.win();await flush();assert.equal(m.events.filter(e=>e.start).length,n,'mute blocks jackpot');m.sound.enabled(true);m.sound.prime();m.sound.spin(0);await flush();assert.equal(m.events.filter(e=>e.start).length,n,'reduced motion skips reels');m.document.hidden=true;m.sound.win();await flush();assert.equal(m.events.filter(e=>e.start).length,n,'hidden page silent');
for(const action of ['stop','close']){let d=make(true);d.sound.prime();d.sound.spin(5200);d.sound[action]();d.pending.forEach(f=>f());await flush();assert(!d.events.some(e=>e.start),'cancel pending decode: '+action)}
let late=make(true);late.sound.prime();late.sound.spin(5200);late.time(1000);late.pending.forEach(f=>f());await flush();assert.equal(late.events.find(e=>e.start).offset,1,'late decoder joins current reel position');
let p=make();p.sound.prime(true);assert.equal(p.events.filter(e=>e.loaded).length,9,'bounded Popcorn pool preloads nine reusable voices');
p.sound.popcornSpin(4220);p.sound.popcornTick(false,true);p.time(125);p.sound.popcornTick(false);p.time(250);p.sound.popcornTick(false);p.time(375);p.sound.popcornTick(false);p.time(2261);p.sound.popcornTick(true);p.time(2429);p.sound.popcornTick(true);p.time(2679);p.sound.popcornTick(true);p.time(2889);p.sound.popcornTick(true);p.time(4220);p.sound.popcornSettle();p.time(4370);p.sound.popcornWin();await flush();
const played=p.events.filter(e=>e.played);
assert.deepEqual(played.map(e=>path.basename(e.played)),['spin-launch.wav','reel-pass-fast.wav','reel-pass-fast.wav','reel-pass-fast.wav','reel-pass-fast.wav','reel-pass-slow.wav','reel-pass-slow.wav','reel-pass-slow.wav','reel-pass-slow.wav','winner-lock.wav','winner-reveal.wav'],'approved files map to launch, real fast/slow crossings, exact lock, and reveal');
assert.equal(played[0].volume,.55);assert.equal(played[1].volume,.18*.65);assert.equal(played[2].volume,.18);assert.equal(played.at(-2).volume,.44);assert.equal(played.at(-1).volume,.78);
assert(!p.events.some(e=>e.paused),'normal Popcorn phase changes never cut a playing tail');assert(!p.events.some(e=>e.start),'Popcorn never starts a Classic source');
let bound=make();bound.sound.prime(true);for(let i=0;i<4;i++)bound.sound.popcornTick(true);assert.equal(bound.events.filter(e=>e.played).length,3,'saturated slow pool drops a cue instead of stealing a live voice');assert(!bound.events.some(e=>e.paused),'pool saturation does not chop a live cue');
let fade=make();fade.sound.prime(true);fade.sound.popcornSpin(4220);const oldId=fade.events.find(e=>e.played).id;fade.sound.stop();assert(!fade.events.some(e=>e.paused&&e.id===oldId),'cancellation begins with a short fade');fade.sound.prime(true);fade.sound.popcornSpin(4220);const newId=fade.events.filter(e=>e.played).at(-1).id;fade.runTimers();assert(fade.events.some(e=>e.paused&&e.id===oldId),'cancellation releases the old voice after the fade');assert(!fade.events.some(e=>e.paused&&e.id===newId),'old fade callbacks cannot stop a new spin');
p.sound.enabled(false);const cueCount=p.events.filter(e=>e.played).length;assert(p.events.some(e=>e.paused),'Sound Off immediately silences active Popcorn voices');p.sound.popcornSpin(4220);p.sound.popcornTick(false);p.sound.popcornTick(true);p.sound.popcornSettle();p.sound.popcornWin();await flush();assert.equal(p.events.filter(e=>e.played).length,cueCount,'Sound Off gates all five approved cues');
console.log('PASS: Classic lifecycle/timing; exact approved Popcorn assets, bounded overlap, natural tails, cancellation fade, and Sound Off. Mock AudioContext/Audio.');
})().catch(e=>{console.error(e);process.exit(1)});
