const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(require('path').resolve(__dirname,'../Jellyfin.Plugin.WatchWheel/Web/watchWheel.js'),'utf8');
const helper=source.slice(source.indexOf('    function createWheelSound()'),source.indexOf('    function value('));
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
function make(delayed=false){let now=0,decodeCount=0;const events=[],pending=[];const document={hidden:false};
class Audio{constructor(){this.state='running';this.destination={};this.currentTime=0;}resume(){this.state='running';return Promise.resolve()}close(){this.state='closed';events.push('close');return Promise.resolve()}decodeAudioData(bytes,yes,no){const duration=decodeCount++%2===0?5.2:3.1;if(delayed)pending.push(()=>yes({duration}));else yes({duration});}createBufferSource(){const s={playbackRate:{value:1},connect(){},disconnect(){},start(t,offset){events.push({start:true,offset,rate:s.playbackRate.value,duration:s.buffer.duration})},stop(){events.push('stop')}};return s}createOscillator(){const s={frequency:{setValueAtTime(f){s.hz=f},exponentialRampToValueAtTime(){}},connect(){},disconnect(){},start(){events.push({cue:s.hz})},stop(){events.push('cue-stop')}};return s}createGain(){return{gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}}}}
class Clip{constructor(url){this.url=url;this.currentTime=0;events.push({loaded:url})}pause(){events.push({paused:this.url})}play(){events.push({played:this.url,volume:this.volume});return Promise.resolve()}}
const scope={window:{AudioContext:Audio,Audio:Clip,ApiClient:{getUrl:x=>x},atob:s=>Buffer.from(s,'base64').toString('binary')},document,performance:{now:()=>now},Uint8Array,Promise};vm.createContext(scope);vm.runInContext(helper+';this.sfx=createWheelSound();',scope);return{sound:scope.sfx,events,pending,document,time:t=>now=t};}
(async()=>{
let m=make();m.sound.spin(5200);await flush();assert.equal(m.events.length,0,'no audio before gesture');m.sound.prime();m.sound.spin(6500);await flush();let start=m.events.find(e=>e.start);assert(Math.abs(start.rate-.8)<.0001,'reels stretched to animation duration');m.sound.win();await flush();assert(m.events.includes('stop'));assert.equal(m.events.filter(e=>e.start).at(-1).duration,3.1);m.sound.enabled(false);const n=m.events.filter(e=>e.start).length;m.sound.win();await flush();assert.equal(m.events.filter(e=>e.start).length,n,'mute blocks jackpot');m.sound.enabled(true);m.sound.prime();m.sound.spin(0);await flush();assert.equal(m.events.filter(e=>e.start).length,n,'reduced motion skips reels');m.document.hidden=true;m.sound.win();await flush();assert.equal(m.events.filter(e=>e.start).length,n,'hidden page silent');
for(const action of ['stop','close']){let d=make(true);d.sound.prime();d.sound.spin(5200);d.sound[action]();d.pending.forEach(f=>f());await flush();assert(!d.events.some(e=>e.start),'cancel pending decode: '+action)}
let late=make(true);late.sound.prime();late.sound.spin(5200);late.time(1000);late.pending.forEach(f=>f());await flush();assert.equal(late.events.find(e=>e.start).offset,1,'late decoder joins current reel position');
let p=make();p.sound.prime(true);p.sound.popcornSpin(3770);p.sound.popcornTick(false,true);p.sound.popcornTick(true);p.sound.popcornSettle();p.sound.popcornLockFade(0);p.sound.popcornWin();await flush();
assert.deepEqual(p.events.filter(e=>e.played).map(e=>e.played),['spin-start','reel-tick','slow-tick','stop','reveal'].map(x=>'WatchWheel/Assets/popcorn-'+x+'-v2.wav'),'Only V2 WAVs are active');
assert.deepEqual(p.events.filter(e=>e.played).map(e=>e.volume),[.52,.20*.65,.32,.48,.72],'matching quiet mix and launch ducking');
assert(!p.events.some(e=>e.start),'Popcorn never starts a Classic source');
p.sound.enabled(false);const cueCount=p.events.filter(e=>e.played).length;
p.sound.popcornSpin(3770);p.sound.popcornTick(false);p.sound.popcornTick(true);p.sound.popcornSettle();p.sound.popcornWin();await flush();
assert.equal(p.events.filter(e=>e.played).length,cueCount,'Sound Off mutes all five V2 cues');
console.log('PASS: Classic lifecycle/timing; five V2 cues, quieter mix, launch ducking, and Sound Off. Mock AudioContext/Audio.');
})().catch(e=>{console.error(e);process.exit(1)});
